Transfers: Main.cpp File Reference
Main.cpp File Reference
#include "tests/Tests.h"
#include "libs/tui/TextUserInterface.h"
#include "classes/TransfersSystem.h"
#include "classes/Map.h"
#include "classes/Service.h"
#include <vector>
#include <stack>
Functions
void readDataFile ()
void changeSettings ()
void mainAppMenu ()
int main ()
Variables
TextUserInterface tui ("Tema 6: Planemanento de Transfers", 70, 15)
TransfersSystem ts (60, 30)
Function Documentation
void changeSettings ()
Definition at line 168 of file Main.cpp.
References TransfersSystem::getBusStocking(), TransfersSystem::getOverhead(), TextUserInterface::print(), TextUserInterface::printInt(), TextUserInterface::printMenu(), TransfersSystem::setBusStocking(), TransfersSystem::setOverhead(), ts, and tui.
Referenced by mainAppMenu().
int main ()
Definition at line 249 of file Main.cpp.
References TextUserInterface::clearScreen(), mainAppMenu(), TextUserInterface::printEnd(), TextUserInterface::printMenu(), TextUserInterface::printSkipFooter(), tests_main(), and tui.
void mainAppMenu ()
Definition at line 202 of file Main.cpp.
References TransfersSystem::calcSimplePath(), changeSettings(), TransfersSystem::getServices(), TextUserInterface::print(), TextUserInterface::printMenu(), readDataFile(), ts, and tui.
Referenced by main().
void readDataFile ()
Definition at line 145 of file Main.cpp.
References TransfersSystem::addDataFromFile(), TextUserInterface::LEFT, TextUserInterface::print(), ts, and tui.
Referenced by mainAppMenu().
Variable Documentation
TransfersSystem ts(60, 30)
Referenced by changeSettings(), mainAppMenu(), and readDataFile().
TextUserInterface tui("Tema 6: Planemanento de Transfers", 70, 15)
Referenced by changeSettings(), main(), mainAppMenu(), and readDataFile().