Transfers: TextUserInterface Class Reference
TextUserInterface Class Reference
#include <TextUserInterface.h>
Public Types
enum Alignment { LEFT, CENTER, RIGHT }
Public Member Functions
void clearScreen ()
TextUserInterface (std::string title, unsigned int width, unsigned int height)
int getWidth ()
std::string print (std::string output, Alignment align=LEFT, std::string msg="", bool menu=false)
int printInt (std::string output, std::string msg, int min, int max, Alignment align=LEFT)
float printFloat (std::string output, std::string msg, float min, float max, Alignment align=LEFT)
void printEnd (std::string output, Alignment align=LEFT)
int printMenu (std::string menu, bool err=false)
void printSkipFooter ()
Static Public Member Functions
static std::vector< std::string > strsplit (std::string str, std::string sep)
static std::string printLine (int size, char c)
static std::string printTextLine (std::string text, Alignment align, unsigned size)
Private Attributes
unsigned int width
unsigned int height
std::string title
Detailed Description
Definition at line 18 of file TextUserInterface.h.
Member Enumeration Documentation
enum TextUserInterface::Alignment
Enumerator
LEFT
CENTER
RIGHT
Definition at line 20 of file TextUserInterface.h.
Constructor & Destructor Documentation
TextUserInterface::TextUserInterface (std::string title, unsigned int width, unsigned int height)
Definition at line 61 of file TextUserInterface.cpp.
Member Function Documentation
void TextUserInterface::clearScreen ()
Definition at line 183 of file TextUserInterface.cpp.
References height.
Referenced by main(), and print().
int TextUserInterface::getWidth () inline
Definition at line 29 of file TextUserInterface.h.
References width.
string TextUserInterface::print (std::string output, Alignment align = LEFT, std::string msg = "", bool menu = false)
Definition at line 97 of file TextUserInterface.cpp.
References CENTER, clearScreen(), height, LEFT, printLine(), printTextLine(), strsplit(), title, and width.
Referenced by changeSettings(), mainAppMenu(), printEnd(), printFloat(), printInt(), printMenu(), and readDataFile().
void TextUserInterface::printEnd (std::string output, Alignment align = LEFT)
Definition at line 189 of file TextUserInterface.cpp.
References print().
Referenced by main().
float TextUserInterface::printFloat (std::string output, std::string msg, float min, float max, Alignment align = LEFT)
Definition at line 155 of file TextUserInterface.cpp.
References print().
int TextUserInterface::printInt (std::string output, std::string msg, int min, int max, Alignment align = LEFT)
Definition at line 141 of file TextUserInterface.cpp.
References print().
Referenced by changeSettings().
string TextUserInterface::printLine (int size, char c) static
Definition at line 67 of file TextUserInterface.cpp.
Referenced by print(), printSkipFooter(), and printTextLine().
int TextUserInterface::printMenu (std::string menu, bool err = false)
Definition at line 169 of file TextUserInterface.cpp.
References LEFT, print(), strsplit(), and verifOp().
Referenced by changeSettings(), main(), and mainAppMenu().
void TextUserInterface::printSkipFooter ()
Definition at line 133 of file TextUserInterface.cpp.
References printLine(), and width.
Referenced by main().
string TextUserInterface::printTextLine (std::string text, Alignment align, unsigned size) static
Definition at line 75 of file TextUserInterface.cpp.
References CENTER, printLine(), and RIGHT.
Referenced by print().
vector< string > TextUserInterface::strsplit (std::string str, std::string sep) static
Definition at line 14 of file TextUserInterface.cpp.
Referenced by TransfersSystem::addDataFromFile(), print(), and printMenu().
Member Data Documentation
unsigned int TextUserInterface::height private
Definition at line 23 of file TextUserInterface.h.
Referenced by clearScreen(), and print().
std::string TextUserInterface::title private
Definition at line 24 of file TextUserInterface.h.
Referenced by print().
unsigned int TextUserInterface::width private
Definition at line 22 of file TextUserInterface.h.
Referenced by getWidth(), print(), and printSkipFooter().
The documentation for this class was generated from the following files:
libs/tui/TextUserInterface.h
libs/tui/TextUserInterface.cpp