Transfers: TransfersSystem Class Reference
TransfersSystem Class Reference
#include <TransfersSystem.h>
Public Member Functions
TransfersSystem (unsigned busStocking, unsigned overhead)
bool addDataFromFile (std::string filename)
void clearData ()
bool calcSimplePath (std::vector< Service * > services2plan, std::queue< Service * > &ret)
unsigned absSoonerTime (Service *)
unsigned absLatterTime (Service *)
bool calcComplexPath (std::vector< Service * > services, std::queue< Service * > &ret)
const std::vector< Service * > & getServices () const
const Map & getMap () const
unsigned getOverhead () const
unsigned getBusStocking () const
void setOverhead (unsigned oh)
void setBusStocking (unsigned bs)
Private Member Functions
bool calcSimplePathRecursive (std::vector< Service * > &srvsLeft, int min, int max, unsigned previousDist, Service *lastSrv, std::queue< Service * > &ret)
bool calcComplexPathRecursive (std::vector< Service * > &srvsLeft, int min, int max, unsigned dist, unsigned stocking, Service *lastSrv, std::queue< Service * > &ret)
Private Attributes
unsigned overhead
Map locals
unsigned busStocking
std::vector< Service * > services
Service * dropPeople
Detailed Description
Definition at line 19 of file TransfersSystem.h.
Constructor & Destructor Documentation
TransfersSystem::TransfersSystem (unsigned busStocking, unsigned overhead)
Definition at line 16 of file TransfersSystem.cpp.
Member Function Documentation
unsigned TransfersSystem::absLatterTime (Service * s)
Definition at line 25 of file TransfersSystem.cpp.
References Service::getArrivalTime(), Map::getBestTravelTime(), Service::getLocal(), and locals.
Referenced by calcComplexPathRecursive(), and calcSimplePathRecursive().
unsigned TransfersSystem::absSoonerTime (Service * s)
Definition at line 20 of file TransfersSystem.cpp.
References Service::getArrivalTime(), Map::getBestTravelTime(), Service::getLocal(), locals, and overhead.
Referenced by calcComplexPathRecursive(), and calcSimplePathRecursive().
bool TransfersSystem::addDataFromFile (std::string filename)
Definition at line 216 of file TransfersSystem.cpp.
References Graph< T >::addVertex(), clearData(), dropPeople, Map::getAirportLocal(), Graph< T >::getVertex(), locals, Map::resetMap(), services, and TextUserInterface::strsplit().
Referenced by readDataFile(), testCalcComplexPath(), testCalcSimplePath(), and testReadFile().
bool TransfersSystem::calcComplexPath (std::vector< Service * > services, std::queue< Service * > & ret)
Definition at line 201 of file TransfersSystem.cpp.
References busStocking, calcComplexPathRecursive(), Graph< T >::getNumVertex(), and locals.
Referenced by testCalcComplexPath().
bool TransfersSystem::calcComplexPathRecursive (std::vector< Service * > & srvsLeft, int min, int max, unsigned dist, unsigned stocking, Service * lastSrv, std::queue< Service * > & ret) private
Definition at line 126 of file TransfersSystem.cpp.
References absLatterTime(), absSoonerTime(), busStocking, dropPeople, Service::getArrivalTime(), Map::getBestTravelTime(), Service::getLocal(), Service::getPeopleQuantity(), Map::getTravelTimeBetween(), locals, and popService().
Referenced by calcComplexPath().
bool TransfersSystem::calcSimplePath (std::vector< Service * > services2plan, std::queue< Service * > & ret)
Definition at line 107 of file TransfersSystem.cpp.
References busStocking, calcSimplePathRecursive(), Graph< T >::getNumVertex(), and locals.
Referenced by mainAppMenu(), and testCalcSimplePath().
bool TransfersSystem::calcSimplePathRecursive (std::vector< Service * > & srvsLeft, int min, int max, unsigned previousDist, Service * lastSrv, std::queue< Service * > & ret) private
Definition at line 48 of file TransfersSystem.cpp.
References absLatterTime(), absSoonerTime(), Service::getArrivalTime(), Map::getBestTravelTime(), Service::getLocal(), Map::getTravelTimeBetween(), locals, and popService().
Referenced by calcSimplePath().
void TransfersSystem::clearData ()
Definition at line 29 of file TransfersSystem.cpp.
References dropPeople, locals, Map::resetMap(), and services.
Referenced by addDataFromFile().
unsigned TransfersSystem::getBusStocking () const inline
Definition at line 55 of file TransfersSystem.h.
References busStocking.
Referenced by changeSettings().
const Map& TransfersSystem::getMap () const inline
Definition at line 48 of file TransfersSystem.h.
References locals.
Referenced by testReadFile().
unsigned TransfersSystem::getOverhead () const inline
Definition at line 51 of file TransfersSystem.h.
References overhead.
Referenced by changeSettings().
const std::vector<Service *>& TransfersSystem::getServices () const inline
Definition at line 44 of file TransfersSystem.h.
References services.
Referenced by mainAppMenu(), testCalcComplexPath(), testCalcSimplePath(), and testReadFile().
void TransfersSystem::setBusStocking (unsigned bs) inline
Definition at line 62 of file TransfersSystem.h.
References busStocking.
Referenced by changeSettings().
void TransfersSystem::setOverhead (unsigned oh) inline
Definition at line 59 of file TransfersSystem.h.
References overhead.
Referenced by changeSettings().
Member Data Documentation
unsigned TransfersSystem::busStocking private
Definition at line 23 of file TransfersSystem.h.
Referenced by calcComplexPath(), calcComplexPathRecursive(), calcSimplePath(), getBusStocking(), and setBusStocking().
Service* TransfersSystem::dropPeople private
Definition at line 25 of file TransfersSystem.h.
Referenced by addDataFromFile(), calcComplexPathRecursive(), and clearData().
Map TransfersSystem::locals private
Definition at line 22 of file TransfersSystem.h.
Referenced by absLatterTime(), absSoonerTime(), addDataFromFile(), calcComplexPath(), calcComplexPathRecursive(), calcSimplePath(), calcSimplePathRecursive(), clearData(), and getMap().
unsigned TransfersSystem::overhead private
Definition at line 21 of file TransfersSystem.h.
Referenced by absSoonerTime(), getOverhead(), and setOverhead().
std::vector<Service *> TransfersSystem::services private
Definition at line 24 of file TransfersSystem.h.
Referenced by addDataFromFile(), clearData(), and getServices().
The documentation for this class was generated from the following files:
classes/TransfersSystem.h
classes/TransfersSystem.cpp