Transfers: Local Class Reference
Local Class Reference
#include <Local.h>
Public Member Functions
Local (const Local &l)
Local (std::string name)
std::string getName () const
void setName (std::string name)
bool operator== (const Local &loc) const
Private Attributes
std::string name
Detailed Description
Classe Local. Esta classe representa um local que poderá ser utilizado como ponto de recolha de passageiros.
Definition at line 17 of file Local.h.
Constructor & Destructor Documentation
Local::Local (const Local & l)
Construtor da classe. Recebe por parametro um Local e cria um clone desse local
Parameters
l local a colonar
Definition at line 10 of file Local.cpp.
References name, and setName().
Local::Local (std::string name)
Construtor da classe. Recebe por parametro uma string que será o nome do local/morada
Parameters
name nome do local/morada
Definition at line 14 of file Local.cpp.
References setName().
Member Function Documentation
std::string Local::getName () const
Esta função retorna o nome do local/morada.
Definition at line 18 of file Local.cpp.
References name.
Referenced by operator==().
bool Local::operator== (const Local & loc) const
Operador igual Compara dois locais e verifica se são iguais (isto é,representem o mesmo local).
Parameters
loc local a comparar com.
Returns
retorna true caso os dois locais sejam iguais (isto é, representem o mesmo local), false, caso cntrário.
Definition at line 25 of file Local.cpp.
References getName().
void Local::setName (std::string name)
Este metodo poderá ser utilizado para alerar o nome/morada de um determinado local.
Parameters
name nome do local/morada
Definition at line 21 of file Local.cpp.
References name.
Referenced by Local().
Member Data Documentation
std::string Local::name private
Nome do local/Morada.
Definition at line 22 of file Local.h.
Referenced by getName(), Local(), and setName().
The documentation for this class was generated from the following files:
classes/Local.h
classes/Local.cpp