Transfers: Map Class Reference
Map Class Reference
#include <Map.h>
Public Member Functions
Map ()
unsigned getBestTravelTime (Local *local)
unsigned getTravelTimeBetween (Local *local1, Local *local2)
Local * getAirportLocal ()
void resetMap ()
bool isEmpty ()
Public Member Functions inherited from Graph< Local * >
vector< Local * > dfs () const
bool addVertex (const Local *&in)
bool addEdge (const Local *&sourc, const Local *&dest, double w, double f=0)
bool removeVertex (const Local *&in)
bool removeEdge (const Local *&sourc, const Local *&dest)
vector< Local * > bfs (Vertex< Local * > *v) const
int maxNewChildren (Vertex< Local * > *v, Local *&inf) const
vector< Vertex< Local * > * > getVertexSet () const
int getNumVertex () const
Vertex< Local * > * getVertex (const Local *&v) const
void resetIndegrees ()
vector< Vertex< Local * > * > getSources () const
int getNumCycles ()
vector< Local * > topologicalOrder ()
vector< Local * > getPath (const Local *&origin, const Local *&dest)
void unweightedShortestPath (const Local *&v)
bool isDAG ()
void bellmanFordShortestPath (const Local *&s)
void dijkstraShortestPath (const Local *&s)
void floydWarshallShortestPath ()
int edgeCost (int vOrigIndex, int vDestIndex)
vector< Local * > getfloydWarshallPath (const Local *&origin, const Local *&dest)
void getfloydWarshallPathAux (int index1, int index2, vector< Local * > &res)
Graph< Local * > clone ()
void resetEdgeFlow ()
Additional Inherited Members
Protected Attributes inherited from Graph< Local * >
vector< Vertex< Local * > * > vertexSet
Detailed Description
Classe Mapa. Representa o mapa de locais segundo um Grafo. As arestas deste mapa devem onter a distancia temporal mais curta (em minutos) entre os diversos locais.
Definition at line 20 of file Map.h.
Constructor & Destructor Documentation
Map::Map ()
Construtor da classe Mapa.
Definition at line 10 of file Map.cpp.
Member Function Documentation
Local * Map::getAirportLocal ()
Esta função retorna um apontador para o local do Aeroporto return apontador para aeroporto
Definition at line 40 of file Map.cpp.
References Graph< Local * >::vertexSet.
Referenced by TransfersSystem::addDataFromFile().
unsigned Map::getBestTravelTime (Local * local)
Esta função retorna o tempo, pelo caminho mais curto, entre um determinado local e o aeroporto.
Parameters
local local a calcular distancia temporal (em minutos)
Returns
distancia temporal (em minutos)
Definition at line 13 of file Map.cpp.
References Graph< Local * >::edgeCost(), and Graph< Local * >::vertexSet.
Referenced by TransfersSystem::absLatterTime(), TransfersSystem::absSoonerTime(), TransfersSystem::calcComplexPathRecursive(), and TransfersSystem::calcSimplePathRecursive().
unsigned Map::getTravelTimeBetween (Local * local1, Local * local2)
Esta função calcula o tempo, pelo caminho mais curto, entre dois determinados determinados locais do mapa.
Parameters
local1 um dos locais
local2 outro dos dois locais
Returns
distancia temporal entre os dois locais (em minutos)
Definition at line 27 of file Map.cpp.
References Graph< Local * >::getVertex().
Referenced by TransfersSystem::calcComplexPathRecursive(), and TransfersSystem::calcSimplePathRecursive().
bool Map::isEmpty ()
Esta funcao retorna verdadeiro se o mapa contiver locais, retorna falso caso contrário.
Definition at line 51 of file Map.cpp.
References Graph< Local * >::vertexSet.
void Map::resetMap ()
Esta funcao elimina todos os vertex do mapa
Definition at line 46 of file Map.cpp.
References Graph< Local * >::vertexSet.
Referenced by TransfersSystem::addDataFromFile(), and TransfersSystem::clearData().
The documentation for this class was generated from the following files:
classes/Map.h
classes/Map.cpp