Transfers: Service Class Reference
Service Class Reference
#include <Service.h>
Public Member Functions
Service (unsigned peopleQuantity, unsigned arrival, Local *local)
bool operator== (const Service &service) const
unsigned getArrivalTime () const
unsigned getPeopleQuantity () const
Local * getLocal () const
Private Attributes
unsigned arrivalTime
Local * local
unsigned peopleQuantity
Detailed Description
Classe Service. Representa um serviço prestado pela empresa. Um serviço é caraterizado por um local de recolha, uma tempo determinado para estar no aeroporto e uma quantidade de pessoas a transportar.
Definition at line 17 of file Service.h.
Constructor & Destructor Documentation
Service::Service (unsigned peopleQuantity, unsigned arrival, Local * local)
Construtor da classe Serviço
Parameters
peopleQuantity quantidade de passageiros a transportar
arrival tempo determinado para estar no aeroporto (numero de minutos desde as 0 horas)
local Local de recolha dos passageiros
Definition at line 10 of file Service.cpp.
References arrivalTime, local, and peopleQuantity.
Member Function Documentation
unsigned Service::getArrivalTime () const
Esta função retorna o tempo determinado para estar no aeroporto (numero de minutos desde as 0 horas)
Returns
tempo determinado para estar no aeroporto (numero de minutos desde as 0 horas)
Definition at line 25 of file Service.cpp.
References arrivalTime.
Referenced by TransfersSystem::absLatterTime(), TransfersSystem::absSoonerTime(), TransfersSystem::calcComplexPathRecursive(), and TransfersSystem::calcSimplePathRecursive().
Local * Service::getLocal () const
Esta função retorna um apontador para o local de recolha dos passageiros
Returns
esta função retorna um apontador para o local de recolha dos passageiros
Definition at line 28 of file Service.cpp.
References local.
Referenced by TransfersSystem::absLatterTime(), TransfersSystem::absSoonerTime(), TransfersSystem::calcComplexPathRecursive(), and TransfersSystem::calcSimplePathRecursive().
unsigned Service::getPeopleQuantity () const
Esta função retorna a quantidade de passageiros a transportar
Returns
Quantidade de passageiros a transportar
Definition at line 21 of file Service.cpp.
References peopleQuantity.
Referenced by TransfersSystem::calcComplexPathRecursive().
bool Service::operator== (const Service & service) const
Operador igual entre serviços. Verifica se dados dois serviços estes são iguais. Admite-se a não existenicia de serviços diferentes com o mesmo numero de passageiros, partindo do mesmo local, com o mesmo exato tempo determinado pra estar no aeroporto.
Parameters
service serviço a comparar com
Returns
retorna verdadeiro caso os serviços representem o mesmo serviço, retorna falso caso contrário.
Definition at line 16 of file Service.cpp.
References arrivalTime, local, and peopleQuantity.
Member Data Documentation
unsigned Service::arrivalTime private
tempo determinado para estar no aeroporto (numero de minutos desde as 0 horas)
Definition at line 22 of file Service.h.
Referenced by getArrivalTime(), operator==(), and Service().
Local* Service::local private
Local de recolha dos passageiros
Definition at line 26 of file Service.h.
Referenced by getLocal(), operator==(), and Service().
unsigned Service::peopleQuantity private
Quantidade de passageiros a transportar
Definition at line 30 of file Service.h.
Referenced by getPeopleQuantity(), operator==(), and Service().
The documentation for this class was generated from the following files:
classes/Service.h
classes/Service.cpp